// Code generated by tygo. DO NOT EDIT.
/**
 * AUTO-GENERATED TypeScript types from Go API
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * To regenerate types, run:
 *   make types
 *
 * Source: backend/api/
 */

//////////
// source: bulk_data.go

/**
 * BulkDataHandler handles bulk data-related HTTP requests
 */
export interface BulkDataHandler {}

//////////
// source: constants.go

/**
 * DefaultCardsPageSize is the default page size for card-heavy endpoints
 */
export const DefaultCardsPageSize = 50;
/**
 * MaxCardsPageSize is the maximum page size for card-heavy endpoints
 */
export const MaxCardsPageSize = 100;
/**
 * MaxBatchIDs is the maximum number of IDs in a batch move/delete operation
 */
export const MaxBatchIDs = 1000;
/**
 * MaxBatchItems is the maximum number of items in a batch create operation
 */
export const MaxBatchItems = 500;
/**
 * Job constants
 */
/**
 * DefaultJobRetentionDays is the default number of days to retain completed jobs
 */
export const DefaultJobRetentionDays = 30;

//////////
// source: dashboard.go

/**
 * DashboardHandler handles dashboard endpoints
 */
export interface DashboardHandler {}
/**
 * DashboardStats represents the statistics for the dashboard
 * tygo:export
 */
export interface DashboardStats {
	total_inventory_cards: number /* int64 */; // Sum of inventory.quantity
	total_wishlist_cards: number /* int64 */; // Sum of list_item.collected_quantity
	total_collection_value: number /* float64 */; // Value from inventory
	total_collected_from_lists: number /* float64 */; // Value of cards collected from lists
	total_remaining_lists_value: number /* float64 */; // Value of cards still needed from lists
	total_storage_locations: number /* int64 */;
	total_lists: number /* int64 */;
	unassigned_cards: number /* int64 */;
}

//////////
// source: data.go

/**
 * CurrentExportVersion is the latest export format version.
 * Bump this when the export schema changes and add a migration function.
 */
export const CurrentExportVersion = 1;
/**
 * DataHandler handles data import and export endpoints
 */
export interface DataHandler {}
/**
 * ExportData represents the full application data export
 * tygo:export
 */
export interface ExportData {
	version: number /* int */;
	exported_at: string;
	storage_locations: ExportStorageLocation[];
	sorting_rules: ExportSortingRule[];
	inventory: ExportInventoryItem[];
	lists: ExportList[];
}
/**
 * ExportStorageLocation represents a storage location in export format
 * tygo:export
 */
export interface ExportStorageLocation {
	ref_id: number /* uint */;
	name: string;
	storage_type: any /* models.StorageType */;
}
/**
 * ExportSortingRule represents a sorting rule in export format
 * tygo:export
 */
export interface ExportSortingRule {
	name: string;
	priority: number /* int */;
	expression: string;
	storage_location_ref_id: number /* uint */;
	enabled: boolean;
}
/**
 * ExportInventoryItem represents an inventory item in export format
 * tygo:export
 */
export interface ExportInventoryItem {
	scryfall_id: string;
	oracle_id: string;
	treatment: string;
	quantity: number /* int */;
	storage_location_ref_id?: number /* uint */;
}
/**
 * ExportList represents a list with its items in export format
 * tygo:export
 */
export interface ExportList {
	ref_id: number /* uint */;
	name: string;
	description?: string;
	items: ExportListItem[];
}
/**
 * ExportListItem represents a list item in export format
 * tygo:export
 */
export interface ExportListItem {
	scryfall_id: string;
	oracle_id: string;
	treatment: string;
	desired_quantity: number /* int */;
	collected_quantity: number /* int */;
}
/**
 * ImportResponse represents the result of an import operation
 * tygo:export
 */
export interface ImportResponse {
	storage_locations_created: number /* int */;
	sorting_rules_created: number /* int */;
	inventory_items_created: number /* int */;
	lists_created: number /* int */;
	list_items_created: number /* int */;
	warnings?: string[];
}

//////////
// source: health.go

/**
 * HealthHandler handles health check endpoints
 */
export interface HealthHandler {}

//////////
// source: inventory.go

/**
 * InventoryHandler handles inventory endpoints
 */
export interface InventoryHandler {}
/**
 * CreateInventoryRequest represents the request body for creating an inventory item
 */
export interface CreateInventoryRequest {
	scryfall_id: string;
	oracle_id: string;
	treatment?: string;
	language?: string;
	quantity: number /* int */;
	storage_location_id?: number /* uint */;
}
/**
 * UpdateInventoryRequest represents the request body for updating an inventory item
 */
export interface UpdateInventoryRequest {
	scryfall_id?: string;
	oracle_id?: string;
	treatment?: string;
	language?: string;
	quantity?: number /* int */;
	storage_location_id?: number /* uint */;
	clear_storage?: boolean;
}
/**
 * InventoryCardsResponse represents paginated card results with inventory data
 * tygo:export
 */
export interface InventoryCardsResponse {
	data: EnhancedCardResult[];
	page: number /* int */;
	page_size: number /* int */;
	total_cards: number /* int */;
	total_pages: number /* int */;
}
/**
 * ExistingPrintingInfo represents info about an existing printing in inventory
 * tygo:export
 */
export interface ExistingPrintingInfo {
	scryfall_id: string;
	treatment: string;
	language: string;
	quantity: number /* int */;
	storage_location?: any /* models.StorageLocation */;
}
/**
 * ByOracleResponse represents the response for checking existing printings
 * tygo:export
 */
export interface ByOracleResponse {
	oracle_id: string;
	printings: ExistingPrintingInfo[];
	locations: any /* models.StorageLocation */[]; // Unique locations where this card exists
}
/**
 * BatchMoveRequest represents the request body for moving multiple inventory items
 * tygo:export
 */
export interface BatchMoveRequest {
	ids: number /* uint */[];
	storage_location_id?: number /* uint */;
}
/**
 * BatchMoveResponse represents the response for batch move operations
 * tygo:export
 */
export interface BatchMoveResponse {
	updated: number /* int */;
}
/**
 * BatchDeleteRequest represents the request body for deleting multiple inventory items
 * tygo:export
 */
export interface BatchDeleteRequest {
	ids: number /* uint */[];
}
/**
 * BatchDeleteResponse represents the response for batch delete operations
 * tygo:export
 */
export interface BatchDeleteResponse {
	deleted: number /* int */;
}
/**
 * ResortRequest represents the request body for re-sorting inventory items
 * tygo:export
 */
export interface ResortRequest {
	ids?: number /* uint */[]; // If empty, resort all items
}
/**
 * ResortMovement represents a single card movement during resort
 * tygo:export
 */
export interface ResortMovement {
	card_name: string;
	treatment: string;
	from_location?: string; // nil means unassigned
	to_location?: string; // nil means unassigned
}
/**
 * ResortResponse represents the response for resort operations
 * tygo:export
 */
export interface ResortResponse {
	processed: number /* int */;
	updated: number /* int */;
	errors: number /* int */;
	movements?: ResortMovement[];
}

//////////
// source: jobs.go

/**
 * JobsHandler handles job-related HTTP requests
 */
export interface JobsHandler {}

//////////
// source: lists.go

/**
 * ListHandler handles list endpoints
 */
export interface ListHandler {}
/**
 * ListSummary represents a list with summary statistics
 * tygo:export
 */
export interface ListSummary {
	id: number /* uint */;
	created_at: string;
	updated_at: string;
	name: string;
	description: string;
	total_items: number /* int */;
	total_cards_wanted: number /* int */;
	total_cards_collected: number /* int */;
	completion_percentage: number /* int */;
}
/**
 * CreateListRequest represents the request body for creating a list
 * tygo:export
 */
export interface CreateListRequest {
	name: string;
	description: string;
}
/**
 * UpdateListRequest represents the request body for updating a list
 * tygo:export
 */
export interface UpdateListRequest {
	name: string;
	description: string;
}
/**
 * EnrichedListItem represents a list item with card data from Scryfall
 * tygo:export
 */
export interface EnrichedListItem {
	id: number /* uint */;
	created_at: string;
	updated_at: string;
	list_id: number /* uint */;
	scryfall_id: string;
	oracle_id: string;
	treatment: string;
	desired_quantity: number /* int */;
	collected_quantity: number /* int */;
	/**
	 * Enriched fields (populated from Scryfall API)
	 */
	name?: string;
	set_name?: string;
	set_code?: string;
	collector_number?: string;
	rarity?: string;
	current_price?: number /* float64 */;
	finishes?: string[];
	frame_effects?: string[];
	promo_types?: string[];
}
/**
 * ListItemsResponse represents paginated list items with aggregate stats
 * tygo:export
 */
export interface ListItemsResponse {
	data: EnrichedListItem[];
	page: number /* int */;
	page_size: number /* int */;
	total_items: number /* int64 */;
	total_pages: number /* int */;
	total_wanted: number /* int */;
	total_collected: number /* int */;
	completion_percent: number /* int */;
	total_collected_value: number /* float64 */;
	total_remaining_value: number /* float64 */;
}
/**
 * CreateListItemRequest represents a single item to add to a list
 * tygo:export
 */
export interface CreateListItemRequest {
	scryfall_id: string;
	oracle_id: string;
	treatment: string;
	desired_quantity: number /* int */;
}
/**
 * CreateItemsBatchRequest represents the request body for batch adding items
 * tygo:export
 */
export interface CreateItemsBatchRequest {
	items: CreateListItemRequest[];
}
/**
 * UpdateListItemRequest represents the request body for updating a list item
 * tygo:export
 */
export interface UpdateListItemRequest {
	desired_quantity?: number /* int */;
	collected_quantity?: number /* int */;
}

//////////
// source: scheduler.go

/**
 * ScheduledTaskInfo represents information about a scheduled task
 * tygo:export
 */
export interface ScheduledTaskInfo {
	name: string;
	type: string; // "bulk_data_update" | "job_cleanup"
	enabled: boolean;
	schedule: string; // e.g., "03:00 daily"
	next_run: string;
	last_run?: string;
	last_job_id?: number /* uint */;
	last_job_status?: string;
}
/**
 * SchedulerHandler handles scheduler-related API requests
 */
export interface SchedulerHandler {}

//////////
// source: search.go

/**
 * SearchHandler handles card search endpoints
 */
export interface SearchHandler {}
/**
 * SearchResponse wraps search results with pagination metadata
 * tygo:export
 */
export interface SearchResponse {
	data: EnhancedCardResult[];
	page: number /* int */;
	total_cards: number /* int */;
	has_more: boolean;
}
/**
 * CardPrices represents card pricing information
 * tygo:export
 */
export interface CardPrices {
	usd?: string;
	usd_foil?: string;
	usd_etched?: string;
	eur?: string;
	eur_foil?: string;
	tix?: string;
}
/**
 * CardResult represents a card in search results
 * tygo:export
 */
export interface CardResult {
	id: string;
	oracle_id: string;
	name: string;
	set_code?: string;
	set_name?: string;
	collector_number?: string;
	image_uri?: string;
	color_identity: string[];
	finishes: string[];
	frame_effects?: string[];
	promo_types?: string[];
	edhrec_rank?: number /* int */;
	prices: CardPrices;
}
/**
 * CardInventoryData represents inventory information for a card
 * tygo:export
 */
export interface CardInventoryData {
	this_printing: import('./models').Inventory[];
	other_printings: import('./models').Inventory[];
	total_quantity: number /* int */;
}
/**
 * EnhancedCardResult represents a card with inventory information
 * tygo:export
 */
export interface EnhancedCardResult extends CardResult {
	inventory: CardInventoryData;
}
/**
 * AutocompleteResponse represents card name autocomplete suggestions
 * tygo:export
 */
export interface AutocompleteResponse {
	suggestions: string[];
}

//////////
// source: set.go

/**
 * SetHandler handles set endpoints
 */
export interface SetHandler {}
/**
 * TriggerImportResponse represents the response from triggering an import
 * tygo:export
 */
export interface TriggerImportResponse {
	message: string;
	job_id: number /* uint */;
}

//////////
// source: settings.go

/**
 * SettingsHandler handles settings-related HTTP requests
 */
export interface SettingsHandler {}

//////////
// source: sorting_rules.go

/**
 * SortingRulesHandler handles sorting rule endpoints
 */
export interface SortingRulesHandler {}
/**
 * CreateSortingRuleRequest represents the request body for creating a sorting rule
 */
export interface CreateSortingRuleRequest {
	name: string;
	priority: number /* int */;
	expression: string;
	storage_location_id: number /* uint */;
	enabled?: boolean;
}
/**
 * UpdateSortingRuleRequest represents the request body for updating a sorting rule
 */
export interface UpdateSortingRuleRequest {
	name?: string;
	priority?: number /* int */;
	expression?: string;
	storage_location_id?: number /* uint */;
	enabled?: boolean;
}
/**
 * EvaluateRequest represents the request body for evaluating a card against rules
 */
export interface EvaluateRequest {
	card_data: { [key: string]: any };
	treatment?: string; // Optional treatment (foil, nonfoil, etched, etc.)
}
/**
 * EvaluateResponse represents the response for rule evaluation
 */
export interface EvaluateResponse {
	matched: boolean;
	storage_location?: any /* models.StorageLocation */;
	error?: string;
}
/**
 * ValidateExpressionRequest represents the request body for validating an expression
 */
export interface ValidateExpressionRequest {
	expression: string;
}
/**
 * ValidateExpressionResponse represents the response for expression validation
 */
export interface ValidateExpressionResponse {
	valid: boolean;
	error?: string;
}
/**
 * BatchUpdatePriorityItem represents a single rule priority update
 */
export interface BatchUpdatePriorityItem {
	id: number /* uint */;
	priority: number /* int */;
}
/**
 * BatchUpdatePrioritiesRequest represents the request body for batch updating priorities
 */
export interface BatchUpdatePrioritiesRequest {
	updates: BatchUpdatePriorityItem[];
}
/**
 * BatchUpdatePrioritiesResponse represents the response for batch priority updates
 */
export interface BatchUpdatePrioritiesResponse {
	updated_count: number /* int */;
	error?: string;
}

//////////
// source: storage.go
/*
Package api provides HTTP handlers for the ShowMyCards REST API.
It contains handlers for inventory, storage, lists, sorting rules, and other endpoints.
*/

/**
 * StorageHandler handles storage location endpoints
 */
export interface StorageHandler {}
/**
 * CreateStorageRequest represents the request body for creating a storage location
 */
export interface CreateStorageRequest {
	name: string;
	storage_type: any /* models.StorageType */;
}
/**
 * StorageLocationWithCount represents a storage location with its card count
 * tygo:export
 */
export interface StorageLocationWithCount {
	id: number /* uint */;
	created_at: string;
	updated_at: string;
	name: string;
	storage_type: any /* models.StorageType */;
	card_count: number /* int */; // Sum of quantities
	item_count: number /* int */; // Count of distinct records
	total_value: number /* float64 */; // USD total value
}
